# Generated by Django 5.1 on 2024-08-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_kreiranja', models.DateTimeField(auto_now_add=True)),
                ('klijent', models.CharField(max_length=100)),
                ('tip_stranke', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=13)),
                ('uredjaj', models.CharField(max_length=70)),
                ('opis_zahteva', models.CharField(max_length=300)),
            ],
        ),
    ]
